config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'home#index'

  resources :warehouses, only: [:show, :new, :create, :edit, :update, :destroy]
  resources :suppliers, only: [:index, :show, :new, :create, :edit, :update]
  resources :product_models, only: [:index, :show, :new, :create]
  resources :orders, only: [:show, :new, :create] do
    get 'search', on: :collection
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :warehouse
  belongs_to :supplier
  belongs_to :user

  validates :code, :estimated_delivery_date, presence: true
  validate :estimated_delivery_date_is_future
  before_validation :generate_code

  private

    def generate_code
      self.code = SecureRandom.alphanumeric(8).upcase
    end

    def estimated_delivery_date_is_future
      if self.estimated_delivery_date.present? && self.estimated_delivery_date <= Date.today
        self.errors.add(:estimated_delivery_date, 'deve ser futura')
      end
    end
end

app/models/product_model.rb
class ProductModel < ApplicationRecord
  belongs_to :supplier

  validates :name, :sku, presence: true
end

app/models/supplier.rb
class Supplier < ApplicationRecord
  validates :brand_name, :corporate_name, :registration_number, :email, presence: true
  validates :registration_number, uniqueness: true
  validates :registration_number, length: { is: 13}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def description
    "#{name} <#{email}>"
  end
end

app/models/warehouse.rb
class Warehouse < ApplicationRecord
  validates :name, :code, :city, :area, :address, :cep, :description, presence: true
  validates :code, uniqueness: true

  def full_description
    "#{code} - #{name}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @warehouses  = Warehouse.all
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :authenticate_user!

  def show
    @order = Order.find params[:id]
  end

  def new
    @order = Order.new
    @warehouses = Warehouse.all
    @suppliers = Supplier.all
  end

  def create
    order_params = params.require(:order).permit(:warehouse_id, :supplier_id, :estimated_delivery_date)
    @order = Order.new order_params
    @order.user = current_user
    if @order.save
      redirect_to @order, notice: 'Pedido registrado com sucesso'
    else
      @warehouses = Warehouse.all
      @suppliers = Supplier.all
      flash.now[:alert] = 'Não foi possível registrar o pedido'
      render :new
    end
  end

  def search
    @code = params[:query]
    @order = Order.find_by(code: @code)
  end
end

app/controllers/product_models_controller.rb
class ProductModelsController < ApplicationController
  before_action :authenticate_user!, only: [:index]

  def index
    @product_models = ProductModel.all
  end

  def show
    @product_model = ProductModel.find params[:id]
  end

  def new
    @product_model = ProductModel.new
    @suppliers = Supplier.all
  end

  def create
    @product_model = ProductModel.new(product_models_params)
    if @product_model.save()
      redirect_to product_model_path(@product_model), notice: 'Modelo de produto cadastrado com sucesso'
    else
      @suppliers = Supplier.all
      flash.now[:notice] = 'Modelo de produto não cadastrado'
      render 'new'
    end
  end

  private
    def product_models_params
      params
        .require(:product_model)
        .permit(:name, :weight, :width, :height, :depth, :sku, :supplier_id)
    end
end

app/controllers/suppliers_controller.rb
class SuppliersController < ApplicationController
  def index
    @suppliers = Supplier.all
  end

  def show
    @supplier = Supplier.find params[:id]
  end

  def new
    @supplier = Supplier.new
  end

  def create
    @supplier = Supplier.new(supplier_params)
    if @supplier.save()
      redirect_to suppliers_path, notice: 'Fornecedor cadastrado com sucesso'
    else
      flash.now[:notice] = 'Fornecedor não cadastrado'
      render 'new'
    end
  end

  def edit
    @supplier = Supplier.find params[:id]
  end

  def update
    @supplier = Supplier.find params[:id]
    if @supplier.update(supplier_params)
      redirect_to supplier_path(@supplier), notice: 'Fornecedor atualizado com sucesso'
    else
      flash.now[:notice] = "Fornecedor não atualizado"
      render 'edit'
    end
  end

  private
    def supplier_params
      params
        .require(:supplier)
        .permit(:corporate_name, :brand_name, :registration_number, :full_address, :city, :state, :email)
    end
end

app/controllers/warehouses_controller.rb
class WarehousesController < ApplicationController
  before_action :set_warehouse, only: [:show, :edit, :update, :destroy]

  def show
  end

  def new
    @warehouse = Warehouse.new
  end

  def create
    @warehouse = Warehouse.new(warehouse_params)

    if @warehouse.save()
      flash[:notice] = 'Galpão cadastrado com sucesso'
      redirect_to root_path
    else
      flash.now[:notice] = 'Galpão não cadastrado'
      render 'new'
    end
  end

  def edit
  end

  def update
    if @warehouse.update(warehouse_params)
      redirect_to warehouse_path(@warehouse.id), notice: "Galpão atualizado com sucesso"
    else
      flash.now[:notice] = 'Não foi possível atualizar o galpão'
      render 'edit'
    end
  end

  def destroy
    @warehouse.destroy
    redirect_to root_path, notice: 'Galpão removido com sucesso'
  end

  private
    def set_warehouse
      @warehouse = Warehouse.find params[:id]
    end

    def warehouse_params
      params.require(:warehouse).permit(:name, :code, :city, :area, :address, :cep, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.erb
<section id="warehouses">
  <h2>Galpões Cadastrados</h2>
  <div>
    <%= link_to 'Cadastrar Galpão', new_warehouse_path %>
  </div>
  <% @warehouses.each do |w| %>
    <h3><%= link_to w.name, warehouse_path(w.id) %></h3>
    <dl>
      <dt>Código:<dt>
      <dd><%= w.code %></dd>
      <dt>Cidade:</dt>
      <dd><%= w.city %></dd>
      <dt>Área:</dt>
      <dd><%= w.area %> m²</dd>
    </dl>
  <% end %>

  <% if @warehouses.empty? %>
    <p>Não existem galpões cadastrados</p>
  <% end %>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WarehouseApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application" %>
  </head>

  <body>
    <header>
      <%= link_to root_path do %>
        <h1>Galpões & Estoque</h1>
      <% end %>
      <nav>
        <ul>
          <li><%= link_to 'Fornecedores', suppliers_path %></li>
          <li><%= link_to 'Modelos de Produtos', product_models_path %></li>
          <li><%= link_to 'Registrar Pedido', new_order_path %></li>
          <% if user_signed_in? %>
            <li>
              <%= current_user.description %> <%= button_to 'Sair', destroy_user_session_path, method: :delete %>
            </li>
          <% else %>
            <li>
              <%= link_to 'Entrar', new_user_session_path %>
            </li>
          <% end %>
          <% if user_signed_in? %>
            <li>
              <%= form_with url: search_orders_path, method: :get do |f|  %>
                <%= f.label :query, 'Buscar Pedido' %>
                <%= f.text_field :query %>
                <%= f.submit 'Buscar' %>
              <% end %>
            </li>
          <% end %>
        </ul>
      </nav>
    </header>

    <main>
      <div>
        <%= flash[:notice] %>
      </div>
      <div>
        <%= flash[:alert] %>
      </div>
      <%= yield %>
    </main>
  </body>
</html>

app/views/orders/new.html.erb
<h2>Registrar Pedido</h2>

<%= form_with model: @order do |f| %>
  <div>
    <%= f.label :warehouse_id %>
    <%= f.collection_select :warehouse_id, @warehouses, :id, :full_description %>
  </div>

  <div>
    <%= f.label :supplier_id %>
    <%= f.collection_select :supplier_id, @suppliers, :id, :corporate_name %>
  </div>

  <div>
    <%= f.label :estimated_delivery_date %>
    <%= f.date_field :estimated_delivery_date %>
    <% @order.errors.full_messages_for(:estimated_delivery_date).each do |msg| %>
      <div><%= msg %></div>
    <% end %>
  </div>

  <div>
    <%= f.submit 'Registrar' %>
  </div>
<% end %>

app/views/orders/search.html.erb
<h2>Resultados da Busca por: <%= @code %></h2>

<% if @order.present? %>
  <p> 1 pedido encontrado </p>

  <dl>
    <dt><%= Order.human_attribute_name(:code) %>:</dt>
    <dd><%= @order.code %></dd>

    <dt><%= Order.human_attribute_name(:warehouse_id) %>:</dt>
    <dd><%= @order.warehouse.full_description %></dd>

    <dt><%= Order.human_attribute_name(:supplier_id) %>:</dt>
    <dd><%= @order.supplier.corporate_name %></dd>
  </dl>
<% end %>

app/views/orders/show.html.erb
<h2>Pedido <%= @order.code %></h2>

<dl>
    <dt><%= Order.human_attribute_name(:warehouse_id)%>:</dt>
    <dd><%= @order.warehouse.full_description %></dd>

    <dt><%= Order.human_attribute_name(:supplier_id) %>:</dt>
    <dd><%= @order.supplier.corporate_name %></dd>

    <dt><%= Order.human_attribute_name(:user_id) %>:</dt>
    <dd><%= @order.user.description %></dd>

    <dt><%= Order.human_attribute_name(:estimated_delivery_date) %>:</dd>
    <dd><%= I18n.localize @order.estimated_delivery_date %></dd>
</dl>

app/views/product_models/index.html.erb
<h2>Modelos de Produtos</h2>

<%= link_to 'Cadastrar Produto', new_product_model_path %>

<% if @product_models.any? %>
  <% @product_models.each do |product| %>
    <div>
      <h3><%= link_to product.name, product_model_path(product) %></h3>
      <dl>
        <dt>SKU:</dt>
        <dd><%= product.sku %></dd>
        <dt>Fornecedor:</dt>
        <dd><%= product.supplier.brand_name %></dd>
      </dl>
    </div>
  <% end %>
<% else %>
  <p>Nenhum produto cadastrado</p>
<% end %>

app/views/product_models/new.html.erb
<h2>Cadastrar Produto</h2>

<%= form_with model: @product_model do |f| %>
  <div>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div>
    <%= f.label :weight %>
    <%= f.number_field :weight %>
  </div>

  <div>
    <%= f.label :width %>
    <%= f.number_field :width %>
  </div>

  <div>
    <%= f.label :height %>
    <%= f.number_field :height %>
  </div>

  <div>
    <%= f.label :depth %>
    <%= f.number_field :depth %>
  </div>

  <div>
    <%= f.label :sku  %>
    <%= f.text_field :sku %>
  </div>

  <div>
    <%= f.label :supplier_id %>
    <%= f.collection_select :supplier_id, @suppliers, :id, :brand_name %>
  </div>

  <div>
    <%= f.submit 'Enviar' %>
  </div>

<% end %>

app/views/product_models/show.html.erb
<div>
  <h2><%= @product_model.name %></h3>
  <dl>
    <dt>SKU:</dt>
    <dd><%= @product_model.sku %></dd>
    <dt>Fornecedor:</dt>
    <dd><%= @product_model.supplier.brand_name %></dd>
    <dt>Dimensões:</dt>
    <dd><%= "#{@product_model.height}cm x #{@product_model.width}cm x #{@product_model.depth}cm" %></dd>
    <dt>Peso:</dt>
    <dd><%= @product_model.weight %>g</dd>
  </dl>
</div>

app/views/suppliers/_form.html.erb
<%= form_with model: supplier do |f| %>
    <div>
      <%= f.label :corporate_name %>
      <%= f.text_field :corporate_name %>
      <% supplier.errors.full_messages_for(:corporate_name).each do |msg| %>
        <div><%= msg %></div>
      <% end %>
    </div>

    <div>
      <%= f.label :brand_name %>
      <%= f.text_field :brand_name %>
      <% supplier.errors.full_messages_for(:brand_name).each do |msg| %>
        <div><%= msg %></div>
      <% end %>
    </div>

    <div>
      <%= f.label :registration_number %>
      <%= f.text_field :registration_number %>
      <% supplier.errors.full_messages_for(:registration_number).each do |msg| %>
        <div><%= msg %></div>
      <% end %>
    </div>

    <div>
      <%= f.label :full_address %>
      <%= f.text_field :full_address %>
      <% supplier.errors.full_messages_for(:full_address).each do |msg| %>
        <div><%= msg %></div>
      <% end %>
    </div>

    <div>
      <%= f.label :city %>
      <%= f.text_field :city %>
      <% supplier.errors.full_messages_for(:city).each do |msg| %>
        <div><%= msg %></div>
      <% end %>
    </div>

    <div>
      <%= f.label :state %>
      <%= f.text_field :state %>
      <% supplier.errors.full_messages_for(:state).each do |msg| %>
        <div><%= msg %></div>
      <% end %>
    </div>

    <div>
      <%= f.label :email %>
      <%= f.email_field :email %>
      <% supplier.errors.full_messages_for(:email).each do |msg| %>
        <div><%= msg %></div>
      <% end %>
    </div>

    <div>
      <%= f.submit 'Enviar' %>
    </div>
<% end %>

app/views/suppliers/edit.html.erb
<h2>Editar Fornecedor</h2>

<%= render 'suppliers/form', supplier: @supplier %>

app/views/suppliers/index.html.erb
<h2>Fornecedores</h2>

<% if @suppliers.any? %>
  <table>
    <thead>
      <tr>
        <th>Nome</th>
        <th>Localização</th>
      </tr>
    </thead>
    <tbody>
      <% @suppliers.each do |supplier| %>
        <tr>
          <td><%= link_to supplier.brand_name, supplier %></td>
          <td><%= supplier.city %> - <%= supplier.state %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <p>Não há fornecedores cadastrados</p>
<% end %>

<%= link_to 'Cadastrar Fornecedor', new_supplier_path %>

app/views/suppliers/new.html.erb
<h2>Novo Fornercedor</h2>

<%= render 'suppliers/form', supplier: @supplier %>

app/views/suppliers/show.html.erb
<h2><%= @supplier.brand_name %></h2>

<dl>
    <dt>Nome corporativo:</dt>
    <dd><%= @supplier.corporate_name %></dd>

    <dt>Número de registro:</dt>
    <dd><%= @supplier.registration_number %></dd>

    <dt>Endereço:</dt>
    <dd><%= @supplier.full_address %></dd>

    <dt>Cidade:</dt>
    <dd><%= @supplier.city %></dd>

    <dt>Estado:</dt>
    <dd><%= @supplier.state %></dd>

    <dt>Email:</dt>
    <dd><%= @supplier.email %></dd>
</dl>

<div>
    <%= link_to 'Editar', edit_supplier_path(@supplier) %>
</div>

app/views/warehouses/_form.html.erb
<%= form_with model: warehouse do |f| %>
  <div>
    <%= f.label :name, 'Nome' %>
    <%= f.text_field :name %>
    <% warehouse.errors.full_messages_for(:name).each do |msg| %>
        <div><%= msg %></div>
    <% end %>
  </div>

  <div>
    <%= f.label :description, 'Descrição' %>
    <%= f.text_area :description %>
    <% warehouse.errors.full_messages_for(:description).each do |msg| %>
        <div><%= msg %></div>
    <% end %>
  </div>

  <div>
    <%= f.label :code, 'Código' %>
    <%= f.text_field :code %>
    <% warehouse.errors.full_messages_for(:code).each do |msg| %>
        <div><%= msg %></div>
    <% end %>
  </div>

  <div>
    <%= f.label :city, 'Cidade' %>
    <%= f.text_field :city %>
    <% warehouse.errors.full_messages_for(:city).each do |msg| %>
        <div><%= msg %></div>
    <% end %>
  </div>

  <div>
    <%= f.label :area, 'Área' %>
    <%= f.number_field :area %>
    <% warehouse.errors.full_messages_for(:area).each do |msg| %>
        <div><%= msg %></div>
    <% end %>
  </div>

  <div>
    <%= f.label :address, 'Endereço' %>
    <%= f.text_field :address %>
    <% warehouse.errors.full_messages_for(:address).each do |msg| %>
        <div><%= msg %></div>
    <% end %>
  </div>

  <div>
    <%= f.label :cep, 'CEP' %>
    <%= f.text_field :cep %>
    <% warehouse.errors.full_messages_for(:cep).each do |msg| %>
        <div><%= msg %></div>
    <% end %>
  </div>

  <div>
    <%= f.submit 'Enviar' %>
  </div>
<% end %>

app/views/warehouses/edit.html.erb
<h2>Editar Galpão</h2>

<%= render 'warehouses/form', warehouse: @warehouse %>

app/views/warehouses/new.html.erb
<h2>Novo Galpão</h2>

<%= render 'warehouses/form', warehouse: @warehouse %>

app/views/warehouses/show.html.erb
<h2>Galpão <%= @warehouse.code %></h2>

<dl>
    <dt>Nome:</dt>
    <dd><%= @warehouse.name %></dd>
    <dt>Cidade:</dt>
    <dd><%= @warehouse.city %></dd>
    <dt>Endereço:</dt>
    <dd><%= @warehouse.address %> CEP: <%= @warehouse.cep %></dd>
    <dt>Área:</dt>
    <dd><%= @warehouse.area %> m²</dd>
</dl>

<div>
<%= link_to 'Editar', edit_warehouse_path(@warehouse.id) %>
<%= button_to 'Remover', warehouse_path(@warehouse.id), method: :delete %>
</div>

<div>
<%= link_to 'Voltar', root_path %>
</div>